cloud_build: false
grpc_url: "http://localhost:8080"

share_build: false
master_addr: "192.168.134.128:9090"

cwd: "~/proj/build"
project_root: "~/proj"
rbe_properties:
  key1: "value1"
  key2: "value2"
self_ipv4_address: "192.168.1.1"
